### ISSUE TITLE
Uncaught Error: Invalid child node: undefined

### ISSUE THREAD

**Issue by skipzero** [mehcode/linter-ui-plus#13]
[Enter steps to reproduce:]

1. Opened a SASS file. with `linter-sass-lint` package.
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [linter-ui-plus](https://github.com/mehcode/linter-ui-plus) package 0.3.2

### Stack Trace

Uncaught Error: Invalid child node: undefined

```
At /Users/civil-zero/.atom/packages/linter-ui-plus/node_modules/etch/lib/dom.js:25

Error: Invalid child node: undefined
    at Proxy.dom (/packages/linter-ui-plus/node_modules/etch/lib/dom.js:25:15)
    at PanelMessage.render (/packages/linter-ui-plus/panel-message.js:87:11)
    at updateSync (/packages/linter-ui-plus/node_modules/etch/lib/component-helpers.js:99:34)
    at Proxy.update (/packages/linter-ui-plus/node_modules/etch/lib/component-helpers.js:62:5)
    at PanelMessage.update (/packages/linter-ui-plus/panel-message.js:30:17)
    at updateComponent (/packages/linter-ui-plus/node_modules/etch/lib/patch.js:52:13)
    at patch (/packages/linter-ui-plus/node_modules/etch/lib/patch.js:16:19)
    at updateChildren (/packages/linter-ui-plus/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/linter-ui-plus/node_modules/etch/lib/patch.js:18:9)
    at updateSync (/packages/linter-ui-plus/node_modules/etch/lib/component-helpers.js:108:20)
    at Proxy.update (/packages/linter-ui-plus/node_modules/etch/lib/component-helpers.js:62:5)
    at PanelSection.update (/packages/linter-ui-plus/panel-section.js:35:17)
    at updateComponent (/packages/linter-ui-plus/node_modules/etch/lib/patch.js:52:13)
    at patch (/packages/linter-ui-plus/node_modules/etch/lib/patch.js:16:19)
    at updateChildren (/packages/linter-ui-plus/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/linter-ui-plus/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/linter-ui-plus/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/linter-ui-plus/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/linter-ui-plus/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/linter-ui-plus/node_modules/etch/lib/patch.js:18:9)
    at updateSync (/packages/linter-ui-plus/node_modules/etch/lib/component-helpers.js:108:20)
    at /packages/linter-ui-plus/node_modules/etch/lib/component-helpers.js:72:7
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:223:15)
    at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
  3x -2:41.2.0 core:select-up (input.hidden-input)
     -2:39.9.0 core:delete (input.hidden-input)
 10x -2:39.4.0 core:move-up (input.hidden-input)
  4x -2:36.3.0 core:select-up (input.hidden-input)
     -2:34.7.0 core:delete (input.hidden-input)
 23x -2:33.6.0 core:move-up (input.hidden-input)
  6x -1:22.8.0 core:undo (input.hidden-input)
  5x -1:15.2.0 core:redo (input.hidden-input)
     -0:50.7.0 docblockr:parse-enter (input.hidden-input)
     -0:50.7.0 editor:newline (input.hidden-input)
     -0:49.8.0 docblockr:parse-enter (input.hidden-input)
     -0:49.8.0 editor:newline (input.hidden-input)
     -0:41 docblockr:parse-enter (input.hidden-input)
     -0:41 editor:newline (input.hidden-input)
     -0:12.4.0 core:backspace (input.hidden-input)
     -0:04.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
aeons-ui 0.0.10 
apex-syntax 0.1.0 
apex-ui 0.2.1 
atom-beautify 0.30.3 
atom-bracket-highlight 0.3.2 
atom-formatter-jsbeautify 1.1.2 
autoclose-html 0.23.0 
busy-signal 1.4.3 
chameleon-ui 0.1.0 
color-picker 2.2.5 
docblockr 0.10.5 
docker 0.7.0 
dracula-syntax 2.0.5 
dracula-ui 0.6.0 
enso-ui 2.1.0 
file-types 0.5.5 
formatter 2.12.4 
glacier-dark-ui 0.5.0 
hydra-syntax-theme 4.0.1 
intentions 1.1.2 
language-babel 2.66.1 
language-docker 1.1.8 
language-dotfiles 1.1.0 
language-ejs 0.4.0 
language-javascript-jsx 0.3.7 
language-jsx 0.1.1 
linter 2.2.0 
linter-eslint 8.2.1 
linter-htmlhint 1.3.3 
linter-json-lint 0.1.2 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.2 
linter-ui-plus 0.3.2 
no-compromise-ui 0.1.2 
pigments 0.39.1 
pristine-ui 1.0.15 
pure-syntax 0.2.1 
seti-ui 1.9.0 
spring-dark-syntax 0.0.4 
tabs-to-spaces 1.0.3 
todo 0.6.0 
todo-show 1.11.0 
vaporwave-ui 0.0.2 
vive-ui 0.2.0 
vivid 1.4.1 
```

**Comment by mehcode** [comment]
Don't have time to look into this till later today but from an initial look the only way I can see this error happening is if `linter-sass-lint` is handing us a v1 message with its `.text` property `undefined` (which is apparently allowed according to the type). This is more of a comment to myself, I'll figure it out later when I get a moment.

**Comment by skipzero** [comment]
Got a new line number today. Not sure if this'll help any, but here's the ST from the last one.
```
    /Users/<user>/.atom/packages/linter-ui-plus/lib/index.js:82
Hide Stack Trace
TypeError: Cannot read property 'indexOf' of undefined
    at subscriptions.add.textEditor.onDidDestroy (/Users/civil-zero/.atom/packages/linter-ui-plus/index.js:82:25)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:584:26)
    at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app/src/model.js:31:64)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:687:24)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:662:18)
    at Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1696:48)
    at atom-workspace.core:close (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:233:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```
The error was thrown from the linter-ui-plus package...

**Comment by mehcode** [comment]
@skipzero That error looks like #11 and should be fixed on master (to be released in the new few hours when I have a chance to look at a couple more things).

**Comment by skipzero** [comment]
Cool. No problem. Thanks for your quick replies! Let me know if I can do anything else to help.

**Comment by Arcanemagus** [comment]
Can confirm that this is triggered by messages that use `.html` instead of `.text`.

**Comment by pablomayobre** [comment]
Mmm... I installed this package and I'm experiencing this error. It says that the issue was reported (pointing to this one), but here is the stacktrace:

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Windows 10 x64
**Thrown From**: [linter-ui-plus](https://github.com/mehcode/linter-ui-plus) package 0.3.2

### Stack Trace

Uncaught Error: Invalid child node: undefined

```
At C:\Users\nano0\.atom\packages\linter-ui-plus\node_modules\etch\lib\dom.js:25

Error: Invalid child node: undefined
    at Proxy.dom (/packages/linter-ui-plus/node_modules/etch/lib/dom.js:25:15)
    at PanelMessage.render (/packages/linter-ui-plus/panel-message.js:87:11)
    at Proxy.initialize (/packages/linter-ui-plus/node_modules/etch/lib/component-helpers.js:32:31)
    at /packages/linter-ui-plus/panel-message.js:24:10)
    at render (/packages/linter-ui-plus/node_modules/etch/lib/render.js:17:25)
    at addChildren (/packages/linter-ui-plus/node_modules/etch/lib/render.js:39:24)
    at render (/packages/linter-ui-plus/node_modules/etch/lib/render.js:29:21)
    at Proxy.initialize (/packages/linter-ui-plus/node_modules/etch/lib/component-helpers.js:40:23)
    at /packages/linter-ui-plus/panel-section.js:29:10)
    at render (/packages/linter-ui-plus/node_modules/etch/lib/render.js:17:25)
    at updateChildren (/packages/linter-ui-plus/node_modules/etch/lib/patch.js:123:34)
    at patch (/packages/linter-ui-plus/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/linter-ui-plus/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/linter-ui-plus/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/linter-ui-plus/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/linter-ui-plus/node_modules/etch/lib/patch.js:18:9)
    at updateSync (/packages/linter-ui-plus/node_modules/etch/lib/component-helpers.js:116:20)
    at /packages/linter-ui-plus/node_modules/etch/lib/component-helpers.js:72:7
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.19.3/resources/app/src/view-registry.js:187:15)
    at ~/AppData/Local/atom/app-1.19.3/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -6:19.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -3:17.7.0 core:confirm (input.hidden-input)
  5x -2:26.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
linter 2.2.0 
linter-eslint 8.2.1 
linter-js-standard 4.0.0 
linter-js-standard-engine 2.1.0 
linter-luacheck 2.0.1 
linter-tslint 1.7.0 
linter-ui-default 1.6.7 
linter-ui-plus 0.3.2 
minimap 4.29.6 
minimap-linter 2.0.2 
```

**Comment by olee** [comment]
Any activity on this issue?
I tested this package a moment ago but directly got that error as well.
The UI of this package is really nice so I'd love to use it if it works.

**Comment by mehcode** [comment]
It needs to be scrapped or retooled as `atom-ide-ui` is the way forward. I'm currently doing what I can to bring the ideas here directly into `atom-ide-ui`.
