### ISSUE TITLE
Uncaught Error: Tried to create a gutter with a name that is already in use.

### ISSUE THREAD

**Issue by CirnoV** [mehcode/linter-ui-plus#26]
**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [linter-ui-plus](https://github.com/mehcode/linter-ui-plus) package 0.3.2

### Stack Trace

Uncaught Error: Tried to create a gutter with a name that is already in use.

```
At C:\Users\sbtek\AppData\Local\atom\app-1.21.2\resources\app\src\gutter-container.js:40

Error: Tried to create a gutter with a name that is already in use.
    at GutterContainer.module.exports.GutterContainer.addGutter (~/AppData/Local/atom/app-1.21.2/resources/app/src/gutter-container.js:40:21)
    at TextEditor.module.exports.TextEditor.addGutter (~/AppData/Local/atom/app-1.21.2/resources/app/src/text-editor.js:3207:41)
    at /packages/linter-ui-plus/editor.js:24:21)
    at atom.workspace.observeTextEditors.textEditor (/packages/linter-ui-plus/index.js:65:22)
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.21.2/resources/app/src/workspace.js:725:15)
    at window.requestIdleCallback (/packages/linter-ui-plus/index.js:60:20)
```

### Commands

```
     -3:07.2.0 core:backspace (input.hidden-input)
     -3:06.6.0 core:save (input.hidden-input)
  3x -2:56.7.0 core:undo (input.hidden-input)
  2x -2:55.2.0 core:save (input.hidden-input)
     -1:52.6.0 core:cut (input.hidden-input)
     -1:50.7.0 core:backspace (input.hidden-input)
     -1:49.3.0 core:save (input.hidden-input)
     -1:49 editor:newline (input.hidden-input)
 24x -1:47.6.0 core:backspace (input.hidden-input)
     -1:37 core:paste (input.hidden-input)
  2x -1:36 core:backspace (input.hidden-input)
     -1:35.5.0 autocomplete-plus:confirm (input.hidden-input)
     -1:35.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:33.4.0 core:save (input.hidden-input)
     -0:22.1.0 settings-view:open (input.hidden-input)
     -0:17.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
atom-beautify 0.30.6 
atom-bracket-highlight 0.3.2 
atom-clock 0.1.15 
atom-material-ui 2.0.6 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-module-import 0.1.3 
autocomplete-modules 1.8.0 
color-picker 2.2.5 
editorconfig 2.2.2 
es6-javascript 1.0.0 
expand-selection-to-quotes 0.11.0 
file-icons 2.1.13 
git-time-machine 1.5.9 
glowing-cursor 0.1.2 
gutter-shadow 1.1.0 
highlight-selected 0.13.1 
indentation-indicator 1.1.0 
javascript-snippets 1.2.1 
language-babel 2.76.4 
language-ejs 0.4.0 
language-generic-config 1.4.0 
language-vue 0.23.1 
linter 2.2.0 
linter-eslint 8.4.0 
linter-htmlhint 1.4.0 
linter-jsonlint 1.3.0 
linter-stylelint 4.0.2 
linter-ui-default 1.6.10 
linter-ui-plus 0.3.2 
one-dark-vivid-syntax 1.8.0 
sync-settings 0.8.3 
```

**Comment by Arcanemagus** [comment]
Likely a side effect of https://github.com/mehcode/linter-ui-plus/issues/21?
